
js_library(
    name = 'jsbase_jquery',
    srcs = [
        'jqueryfetcher.js'
    ],
    name_in_depended = 'jsbase-depending',
    is_closure_based = True,
    check_code_style = True
)

js_library(
    name = 'jsbase_bootstrap',
    srcs = [
        'bootstrapdialog.js',
        'bootstrapdialog.soy',
    ],
    name_in_depended = 'jsbase-depending',
    is_closure_based = True,
    check_code_style = True
)

js_library(
    name = 'jsbase_semanticui',
    srcs = [
        'semanticui.soy',
        'semanticuidialog.js',
        'semanticuipaginationview.js',
    ],
    name_in_depended = 'jsbase-depending',
    is_closure_based = True,
    check_code_style = True
)

js_library(
    name = 'jsbase_ztree',
    srcs = [
        'biglogleftztreebar.js',
        'biglogleftztreebar.soy',
        'ztreewrapper.js',
    ],
    name_in_depended = 'jsbase-depending',
    is_closure_based = True,
    check_code_style = True
)

